# Numpy Basics

In [2]:
import numpy as np

In [3]:
# To create a numpy array
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [4]:
my_array_one = np.array([34, 88, 90])
my_array_one

array([34, 88, 90])

In [5]:
# Creating multidimensional array
multidimensional_array = np.array([my_array, my_array_one])
multidimensional_array

array([[ 1,  2,  3],
       [34, 88, 90]])

In [6]:
multidimensional_array.dtype

dtype('int64')

In [7]:
multidimensional_array.shape

(2, 3)

In [8]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Arrange values
np.arange(5, 100, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

When we change a slice of an array, the whole array would be changed.

In [11]:
# Making an array with a set of numbers
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Slicing an array
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_of_arr[:] = 99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

Here see that the changes occured as mentioned before.

### Array transposition


In [14]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr_transpose = arr.T
arr_transpose

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
# Taking the dot product
dot_product = np.dot(arr, arr_transpose)
dot_product

array([[ 30,  80],
       [ 80, 255]])

In [19]:
three_dimension = np.arange(30).reshape(5, 2, 3)
three_dimension

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [27]:
three_dimension.swapaxes(0,2)

array([[[ 0,  6, 12, 18, 24],
        [ 3,  9, 15, 21, 27]],

       [[ 1,  7, 13, 19, 25],
        [ 4, 10, 16, 22, 28]],

       [[ 2,  8, 14, 20, 26],
        [ 5, 11, 17, 23, 29]]])